### ISSUE TITLE
Cannot load JRE

### ISSUE THREAD

**Issue by curtisd0886** [mbeccuti/4SeqGUI#1]
I am having issues getting this to run on a Ubuntu machine. I have tried running the software using the script as mentioned in the install file but I get this error: 
Exception in thread "main" java.lang.Error: Cannot load com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel
        at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1406)
        at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1517)
        at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1483)
        at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1056)
        at java.desktop/javax.swing.JPopupMenu.updateUI(JPopupMenu.java:220)
        at java.desktop/javax.swing.JPopupMenu.<init>(JPopupMenu.java:188)
        at java.desktop/javax.swing.JPopupMenu.<init>(JPopupMenu.java:173)
        at pkg4seqgui.MainFrame$DefaultContextMenu.<init>(MainFrame.java:8169)
        at pkg4seqgui.MainFrame.<clinit>(MainFrame.java:8339)

I all so tried to execute the .jar file in the disc folder but go this error:
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
        at pkg4seqgui.MainFrame.<init>(MainFrame.java:550)
        at pkg4seqgui.MainFrame$240.run(MainFrame.java:7396)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 15 more

Any ideas what could be causing this? I have Oracle Java SDK 11 installed and I even installed JavaFX as well just to be sure that wasn't it.

**Comment by kendomaniac** [comment]
Hi 
You need to install the java 8 from Oracle.
Cheers
Raf


Prof. Raffaele A Calogero
Tel +39 3333827080
Email raffaele.calogero@unito.it
 raffaele.calogero@gmail.com
